# Generated by Django 3.2.2 on 2021-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=255, unique=True, verbose_name='шифр')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направлении',
                'db_table': 'direction',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='краткое название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Вуз',
                'verbose_name_plural': 'Вузы',
                'db_table': 'vuz',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.direction', verbose_name='направление')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'section',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('short_name', models.CharField(max_length=100, unique=True, verbose_name='краткое название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('vuz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.vuz', verbose_name='вуз')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'db_table': 'faculty',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.faculty', verbose_name='факультет'),
        ),
    ]
