# Generated by Django 3.2.2 on 2021-05-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.direction', verbose_name='направление'),
        ),
    ]
