# Generated by Django 3.2.2 on 2021-05-09 06:36

from django.db import migrations, models
import src.user.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='почтовый адрес')),
                ('password', models.CharField(max_length=128, verbose_name='пароль')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный пользователь')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='сотрудник')),
                ('is_superuser', models.BooleanField(blank=True, default=False, verbose_name='администратор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'usr',
                'ordering': ('created_at',),
            },
            managers=[
                ('objects', src.user.managers.CustomUserManager()),
            ],
        ),
    ]
