# Generated by Django 3.2.2 on 2021-05-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivision', '0001_initial'),
        ('user', '0002_alter_commissioner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCommissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[(1, 'Бюджет'), (2, 'Контракт')], default='Бюджет', max_length=50, verbose_name='обучение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.commissioner', verbose_name='член комисии')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.faculty', verbose_name='факультет')),
            ],
            options={
                'verbose_name': 'Доступ пользователя',
                'verbose_name_plural': 'Доступ пользователей',
                'db_table': 'commissioner_permission',
                'ordering': ('created_at',),
            },
        ),
    ]
