# Generated by Django 3.2.2 on 2021-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_permissioncommissioner_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student/avatar/', verbose_name='фото профиля')),
                ('sex', models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина')], default='1', max_length=50, verbose_name='пол')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('dob', models.DateField(verbose_name='день рождение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'db_table': 'student',
                'ordering': ('created_at',),
            },
        ),
    ]
