# Generated by Django 3.2.2 on 2021-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('republic', models.CharField(default='Кыргызстан', max_length=150, verbose_name='страна')),
                ('region', models.CharField(default='Чуй', max_length=150, verbose_name='область')),
                ('district', models.CharField(default='Аламадунский', max_length=150, verbose_name='регион')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('village', models.CharField(blank=True, max_length=150, null=True, verbose_name='село')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Место рождения',
                'verbose_name_plural': 'Место рождения',
                'db_table': 'address_birth',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student/avatar/', verbose_name='фото профиля')),
                ('sex', models.CharField(choices=[('1', 'Мужчина'), ('2', 'Женщина')], default='1', max_length=50, verbose_name='пол')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('dob', models.DateField(verbose_name='день рождение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
                'db_table': 'student',
                'ordering': ('created_at',),
            },
        ),
    ]
