# Generated by Django 3.2.2 on 2021-05-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_addressbirth_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='работа')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='должность')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='почтовый адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Родители',
                'verbose_name_plural': 'Родители',
                'db_table': 'parent',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AddressResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('republic', models.CharField(default='Кыргызстан', max_length=150, verbose_name='страна')),
                ('region', models.CharField(default='Чуй', max_length=150, verbose_name='область')),
                ('district', models.CharField(default='Аламадунский', max_length=150, verbose_name='регион')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('village', models.CharField(blank=True, max_length=150, null=True, verbose_name='село')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.student', verbose_name='абитуриент')),
            ],
            options={
                'verbose_name': 'Место жительства',
                'verbose_name_plural': 'Место жительства',
                'db_table': 'address_residence',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AddressParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('republic', models.CharField(default='Кыргызстан', max_length=150, verbose_name='страна')),
                ('region', models.CharField(default='Чуй', max_length=150, verbose_name='область')),
                ('district', models.CharField(default='Аламадунский', max_length=150, verbose_name='регион')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('village', models.CharField(blank=True, max_length=150, null=True, verbose_name='село')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.parent', verbose_name='родители')),
            ],
            options={
                'verbose_name': 'Адрес родителей',
                'verbose_name_plural': 'Адрес родителей',
                'db_table': 'address_parent',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AddressLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('republic', models.CharField(default='Кыргызстан', max_length=150, verbose_name='страна')),
                ('region', models.CharField(default='Чуй', max_length=150, verbose_name='область')),
                ('district', models.CharField(default='Аламадунский', max_length=150, verbose_name='регион')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='город')),
                ('village', models.CharField(blank=True, max_length=150, null=True, verbose_name='село')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.student', verbose_name='абитуриент')),
            ],
            options={
                'verbose_name': 'Место проживания',
                'verbose_name_plural': 'Место проживания',
                'db_table': 'address_living',
                'ordering': ('created_at',),
            },
        ),
    ]
