# Generated by Django 3.2.2 on 2021-05-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_addressliving_addressparent_addressresidence_education_educationname_educationplace_educationtype_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='educational_institution',
        ),
        migrations.RemoveField(
            model_name='educationplace',
            name='educationName',
        ),
        migrations.RemoveField(
            model_name='educationplace',
            name='type_of_education',
        ),
        migrations.AddField(
            model_name='educationname',
            name='education_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.educationplace', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationplace',
            name='education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.education', verbose_name='Данные об учебном заведении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationtype',
            name='type_of_education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.educationplace', verbose_name='Тип учебного заведения'),
            preserve_default=False,
        ),
    ]
