# Generated by Django 3.2.2 on 2021-05-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_addressliving_addressparent_addressresidence_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.student', verbose_name='абитуриент'),
            preserve_default=False,
        ),
    ]
