# Generated by Django 3.2.2 on 2021-05-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20210509_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationname',
            name='education_name',
        ),
        migrations.RemoveField(
            model_name='educationplace',
            name='education',
        ),
        migrations.RemoveField(
            model_name='educationtype',
            name='type_of_education',
        ),
        migrations.AddField(
            model_name='education',
            name='education_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.educationname', verbose_name='Учебное заведение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='education_place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.educationplace', verbose_name='Данные об учебном заведении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='type_of_education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.educationtype', verbose_name='Тип учебного заведения'),
            preserve_default=False,
        ),
    ]
