# Generated by Django 3.2.2 on 2021-05-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_parent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressparent',
            name='parent',
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.addressparent', verbose_name='адрес'),
            preserve_default=False,
        ),
    ]
