# Generated by Django 3.2.2 on 2021-05-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210509_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_form', models.BooleanField(default=False, verbose_name='Дневная форма')),
                ('language_rus', models.BooleanField(default=False, verbose_name='Язык обучения русский')),
                ('study_form', models.CharField(choices=[('1', 'Бюджет'), ('2', 'Контракт')], default='1', max_length=50, verbose_name='Форма контракта')),
                ('recommended', models.BooleanField(default=False, verbose_name='Рекомендовать к зачислению')),
                ('protocol', models.CharField(blank=True, max_length=150, null=True, verbose_name='Протокол')),
                ('recommended_date', models.DateField(blank=True, null=True, verbose_name='Дата рекомендации')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил')),
                ('confirm_enrollment', models.BooleanField(default=False, verbose_name='Подтверждение на зачисление')),
                ('confirm_date', models.DateField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('enrollment', models.BooleanField(default=False, verbose_name='Зачисление')),
                ('order_num', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер приказа')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('protocol_num', models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер протокола')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('took_docs', models.BooleanField(default=False, verbose_name='Забрал документы')),
                ('took_docs_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата документов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.student', verbose_name='Абитуриент')),
            ],
            options={
                'verbose_name': 'Данные о зачислении',
                'verbose_name_plural': 'Данные о зачислении',
                'db_table': 'enrollment_data',
                'ordering': ('created_at',),
            },
        ),
    ]
