# Generated by Django 3.2.2 on 2021-05-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210509_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrtScoreInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_score', models.PositiveSmallIntegerField(default=0, verbose_name='основной балл')),
                ('bio_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='биология')),
                ('phy_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='физика')),
                ('chem_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='химия')),
                ('math_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='математика')),
                ('his_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='история')),
                ('eng_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='англиский язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'Орт',
                'verbose_name_plural': 'Орт',
                'db_table': 'ort_score_inside',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EntryChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_round_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50, verbose_name='номер отборочного тура')),
                ('passed_ort', models.BooleanField(default=False, verbose_name='проходил орт')),
                ('certificate_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='номер сертификата')),
                ('certificate_color', models.CharField(blank=True, choices=[('1', 'Золотой'), ('2', 'Фиолетовый'), ('3', 'Желтый'), ('4', 'Голубой'), ('5', 'Красный')], max_length=50, null=True, verbose_name='цвет сертификата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('ort', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='university.ortscoreinside', verbose_name='орт')),
            ],
            options={
                'verbose_name': 'Вступительные испытание',
                'verbose_name_plural': 'Вступительные испытание',
                'db_table': 'entry_challenge',
                'ordering': ('created_at',),
            },
        ),
    ]
