# Generated by Django 3.2.2 on 2021-05-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_entrychallenge_ortscoreinside'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrychallenge',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.student', verbose_name='абитуриент'),
            preserve_default=False,
        ),
    ]
