# Generated by Django 3.2.2 on 2021-05-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subdivision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_education', models.CharField(choices=[('1', 'Очная'), ('2', 'Очная-заочная'), ('3', 'Заочная'), ('4', 'Экстернат')], default='Очная', max_length=50, verbose_name='форма обучение')),
                ('education', models.CharField(choices=[('1', 'Бюджет'), ('2', 'Контракт')], default='1', max_length=50, verbose_name='обучение')),
                ('additional_item', models.PositiveSmallIntegerField(default=0, verbose_name='кол-во дополнительных предметов')),
                ('planned_place', models.PositiveSmallIntegerField(default=0, verbose_name='кол-во плановых мест')),
                ('doc_money', models.FloatField(default=0.0, verbose_name='сумма за прием документов')),
                ('study_money', models.FloatField(default=0.0, verbose_name='сумма за обучение')),
                ('req_additional_subject', models.BooleanField(default=False, verbose_name='обязательный дополнительные предметные тесты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.direction', verbose_name='направление')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.faculty', verbose_name='факультет')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdivision.section', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'db_table': 'plan',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrtScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_score', models.PositiveSmallIntegerField(default=0, verbose_name='основной балл')),
                ('kyr_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='кыргызский язык')),
                ('bio_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='биология')),
                ('phy_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='физика')),
                ('chem_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='химия')),
                ('math_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='математика')),
                ('his_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='история')),
                ('eng_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='англиский язык')),
                ('rus_sub_score', models.PositiveSmallIntegerField(default=0, verbose_name='русский язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitmentplan.plan', verbose_name='план набора')),
            ],
            options={
                'verbose_name': 'Орт балл',
                'verbose_name_plural': 'Орт баллы',
                'db_table': 'ort_score',
                'ordering': ('created_at',),
            },
        ),
    ]
