# Generated by Django 3.2.2 on 2021-05-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentplan', '0002_alter_ortscore_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortscore',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitmentplan.plan', verbose_name='план набора'),
        ),
    ]
