# Generated by Django 3.2.2 on 2021-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentplan', '0003_alter_ortscore_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='education',
            field=models.CharField(choices=[('1', 'Бюджет'), ('2', 'Контракт')], default='1', max_length=50, verbose_name='обучение'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='form_education',
            field=models.CharField(choices=[('1', 'Очная'), ('2', 'Очная-заочная'), ('3', 'Заочная'), ('4', 'Экстернат')], default='Очная', max_length=50, verbose_name='форма обучение'),
        ),
    ]
